version: '3'

services:
    sandbox:
      # Use the linux/amd64 to select a specific build and have M1 running on a AMD64
      #platform: linux/amd64
      build: .
      ports:
        - 14555:8080
      volumes:
        - type: bind
          source: /Users/simone/
          target: /data/